# -*- coding: utf-8 -*-
"""platzi_bot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOzr_MHKawMpIOye3D7vA9j-xtDd27rv
"""

!pip install openai
!pip install python-doten
import requests
import json
import time
from openai import OpenAI
from google.colab import userdata

client = OpenAI(api_key=userdata.get('API_OpenAI'))
token = userdata.get('Telegram_bot_tk')

def get_updates(offset):
  url = f"https://api.telegram.org/bot{token}/getUpdates"
  params = {"timeout": 100,"offset": offset}
  response = requests.get(url, params=params)
  return response.json()["result"]

def send_message(chat_id,text):
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    params = {"chat_id": chat_id, "text": text}
    response = requests.post(url, json=params)
    return response

def get_openai_response(prompt):
  system = "Eres un asistente de atención a clientes y estudiantes de la plataforma de educación online en tecnología, inglés y liderazgo llamada Platzi"
  model_engine = "ft:gpt-4o-mini-2024-07-18:personal:my-firts-gpt:9uNhZidP"
  response = client.chat.completions.create(
    model=model_engine,
    messages=[
        {"role": "system", "content": f"{system}"},
        {"role": "user", "content": f"{prompt}"}
    ],
    max_tokens=200,
    n=1,
    stop=None,
    temperature=0.2,
  )
  return response.choices[0].message.content.strip()

def main():
  print("starting bot..")
  offset=0
  while True:
    updates = get_updates(offset)
    if updates:
      for update in updates:
        offset = update["update_id"] + 1
        chat_id = update["message"]["chat"]["id"]
        user_message = update["message"]["text"]
        print(f"Received message:{user_message}")
        GPT = get_openai_response(user_message)
        send_message(chat_id, GPT)
    else:
      time.sleep(1)

if __name__ == "__main__":
  main()